### ISSUE TITLE
PATH variable lost when issuing new command

### ISSUE THREAD

**Issue by ZaphodBBX** [steelbrain/node-ssh#111]
I had some troubles getting a correct path setup using node-ssh.
This is an example of something i tried:
```
ssh.execCommand('export PATH="$PATH:/something/to/be/added/bin"', [], {})
    .then(function(result) {
      ssh.execCommand( "echo $PATH" , [], { } )
        .then(function(out){
          console.log(out.stdout);
          //will output path does not contain /something/to/be/added/bin
          ssh.dispose();
        });
    });
```
I also tried updating my _~/.bash_profile_ and _~/.bashrc_ files to set the path correctly, and even explicitly sourced these files via the .execCommand("source ~/.bash_profile") but to no avail. Every subsequent lost the path variables set in the original one.

Not sure if this is an issue or wanted behaviour (to not pollute env), but how should you make sure node-ssh has the correct environment?

**Comment by andrejcremoznik** [comment]
I'm not 100% sure what you want to do. If you need to access env vars locally (where you're running node), you can do that through node's `process.env` e.g. `const localEnvPath = process.env.PATH`.

If you need to modify PATH on remote because some binary you're executing through `execCommand` needs it, then your server needs to first be configured to accept [user's environment](https://superuser.com/questions/48783/how-can-i-pass-an-environment-variable-through-an-ssh-command).

> but how should you make sure node-ssh has the correct environment?

The environment will be exactly as you'd expect for the user executing (locally) or user connecting (remote). If the values you need are static, just set them in `.bashrc` on remote (at the very top of the file, before the usual exit statement for non-interactive shells).

**Comment by steelbrain** [comment]
Thanks for answering this @andrejcremoznik 

Just as @andrejcremoznik, when you ssh into a machine, you are into that machine's users' shell. You no longer have your local environment variables or local binaries to execute.
