### ISSUE TITLE
Interactive Shell

### ISSUE THREAD

**Issue by cemalgnlts** [steelbrain/node-ssh#441]
Hi,

On some servers it shows a message after logging in or asking me to press a key on the keyboard before logging in.
When the command comes with `exec`, it gives an error and does not accept it. But if I do this with stream it's fine.

If I use it like this after the connection, when the connection is successful, I can get a welcome message from the terminal:
```js
ssh.withShell(channel => {
   channel.on("data", data => {
      console.log(data.toString())
   });
});
```

The problem is that it's not async, I don't have a socket connection and when I want the result of a command I have to wait for the stream's response.

Is there a method that will work async for streams?

Thanks.

**Comment by steelbrain** [comment]
Hello hello!

I saw you closed that issue, does it mean you figured out what the problem was? If so, I'd request that you still post the answer so future visitors may be able to learn from the experience.

I took a quick look at the code and it seems to me that we are using the incorrect function for the job, the purpose of `withShell` is to have a promise-returning callback that returns only when the shell is no longer necessary, and thus should be disposed of. In this usecase, the callback is synchronous and doesn't block anything so the shell is immediately disposed.

We should replace the usage with the other, `requestShell` which supports this usecase and requires you to close it manually

**Comment by cemalgnlts** [comment]
I closed the thread because I thought I was asking the wrong question.

When we use `execCommand`, it returns us the result of the command. For example if I type `ls` it returns me the whole result in one go.

But if this is done with a shell, it returns me line by line, not all at once. In this case, it didn't seem right to get the result by just making a request. As you said, I used `requestShell` and got a much better result with the help of a socket.

Thanks.
